import type { Metadata } from "next";
import { Geist, Geist_Mono, Timmana } from "next/font/google";
import "./globals.css";
import MantineClientProvider from "@/components/MantineClientProvider";

import "@mantine/core/styles.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const timmana = Timmana({
  weight: "400",
  variable: "--font-timmana",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${timmana.variable} antialiased`}
      >
        <MantineClientProvider>{children}</MantineClientProvider>
      </body>
    </html>
  );
}
